<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://www.mindefensa.gov.co/xsd/Operacion/CambiarContraseña/V1.0" xmlns:ns0="http://ws.ani.rnec.gov.co/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:hdr="http://www.amx.com/CO/Schema/MinDefensaHeaders/v1" xmlns:ns1="http://xmlns.mindefensa.gov.co/xsd/Headers/v1">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/WSConsultaV1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="cambiarContrasenaResponse" namespace="http://ws.ani.rnec.gov.co/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/PS_CON_CambiarContrasenaV1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="cambiarContrasenaResponse" namespace="http://www.mindefensa.gov.co/xsd/Operacion/CambiarContraseña/V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUL 13 15:24:31 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:cambiarContrasenaResponse>
         <tns:return>
            <tns:estadoCambioClave>
               <tns:numeroControl>
                  <xsl:value-of select="/ns0:cambiarContrasenaResponse/return/estadoCambioClave/numeroControl"/>
               </tns:numeroControl>
               <tns:codError>
                  <xsl:value-of select="/ns0:cambiarContrasenaResponse/return/estadoCambioClave/codError"/>
               </tns:codError>
               <tns:descripcionError>
                  <xsl:value-of select="/ns0:cambiarContrasenaResponse/return/estadoCambioClave/descripcionError"/>
               </tns:descripcionError>
               <tns:fechaHoraConsulta>
                  <xsl:value-of select="/ns0:cambiarContrasenaResponse/return/estadoCambioClave/fechaHoraConsulta"/>
               </tns:fechaHoraConsulta>
            </tns:estadoCambioClave>
         </tns:return>
      </tns:cambiarContrasenaResponse>
   </xsl:template>
</xsl:stylesheet>