<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.www.mindefensa.gov.co/xsd/CON/Operacion/ConsultarCedulas/V1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://www.www.mindefensa.gov.co/xsd/Operacion/WSConsulta/V1.0" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:hdr="http://www.amx.com/CO/Schema/MinDefensaHeaders/v1"
                xmlns:ns1="http://xmlns.mindefensa.gov.co/xsd/Headers/v1"
                xmlns:ns2="http://www.www.mindefensa.gov.co/xsd/Operacion/ConsultarCedulas/V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../CON_RegistraduriaNacional/WSConsulta/Resources/Schemas/PS_CON_ConsultarCedulaV1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarCedulasResponse" namespace="http://www.www.mindefensa.gov.co/xsd/CON/Operacion/ConsultarCedulas/V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/PS_ConsultarCedulasV1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="headerResponse" namespace="http://www.www.mindefensa.gov.co/xsd/Operacion/ConsultarCedulas/V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUL 13 17:03:25 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
   <xsl:choose>
        <xsl:when test="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:codError = '0'">
      <tns:headerResponse>
         <hdr:codigo>
                  OK
         </hdr:codigo>
         <hdr:descripcion>
            <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:descripcionError"/>
         </hdr:descripcion>
         <hdr:fechaRespuesta>
                  <xsl:value-of select="xp20:current-dateTime ( )"/>
         </hdr:fechaRespuesta>
         <hdr:idTransaccion>
                  <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:numeroControl"/>
               </hdr:idTransaccion>
      </tns:headerResponse>
      </xsl:when>
      <xsl:otherwise>
       <tns:headerResponse>
         <hdr:codigo>
                  WR
         </hdr:codigo>
         <hdr:descripcion>
            <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:descripcionError"/>
         </hdr:descripcion>
         <hdr:fechaRespuesta>
                  <xsl:value-of select="xp20:current-dateTime ( )"/>
         </hdr:fechaRespuesta>
         <hdr:idTransaccion>
                  <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:numeroControl"/>
        </hdr:idTransaccion>
         <hdr:Error>
            <hdr:codigoError>
                     <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:codError"/>
                  </hdr:codigoError>
            <hdr:DescripcionError>
                     <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:descripcionError"/>
            </hdr:DescripcionError>
            <hdr:tipoError>
              [CON-API]-ConsultarCedulas
            </hdr:tipoError>
         </hdr:Error>
      </tns:headerResponse>
      </xsl:otherwise>
      </xsl:choose>
   </xsl:template>
</xsl:stylesheet>