<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.www.mindefensa.gov.co/xsd/CON/Operacion/ConsultarCedulas/V1.0" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://www.www.mindefensa.gov.co/xsd/Operacion/WSConsulta/V1.0" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:hdr="http://www.amx.com/CO/Schema/MinDefensaHeaders/v1" xmlns:ns1="http://xmlns.mindefensa.gov.co/xsd/Headers/v1" xmlns:ns2="http://www.www.mindefensa.gov.co/xsd/Operacion/ConsultarCedulas/V1.0">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../CON_RegistraduriaNacional/WSConsulta/Resources/Schemas/PS_CON_ConsultarCedulaV1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarCedulasResponse" namespace="http://www.www.mindefensa.gov.co/xsd/CON/Operacion/ConsultarCedulas/V1.0"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/PS_ConsultarCedulasV1.0.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarCedulasResponse" namespace="http://www.www.mindefensa.gov.co/xsd/Operacion/ConsultarCedulas/V1.0"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [MON JUL 13 15:32:40 COT 2020].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:consultarCedulasResponse>
         <tns:return>
            <tns:estadoConsulta>
               <tns:numeroControl>
                  <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:numeroControl"/>
               </tns:numeroControl>
               <tns:codError>
                  <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:codError"/>
               </tns:codError>
               <tns:descripcionError>
                  <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:descripcionError"/>
               </tns:descripcionError>
               <tns:fechaHoraConsulta>
                  <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:estadoConsulta/ns0:fechaHoraConsulta"/>
               </tns:fechaHoraConsulta>
            </tns:estadoConsulta>
            <xsl:if test="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas">
               <tns:datosCedulas>
                  <tns:datos xsi:nil="{/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/@xsi:nil}">
                     <tns:nuip>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:nuip"/>
                     </tns:nuip>
                     <tns:codError>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:codError"/>
                     </tns:codError>
                     <tns:primerApellido>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:primerApellido"/>
                     </tns:primerApellido>
                     <tns:particula>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:particula"/>
                     </tns:particula>
                     <tns:segundoApellido>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:segundoApellido"/>
                     </tns:segundoApellido>
                     <tns:primerNombre>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:primerNombre"/>
                     </tns:primerNombre>
                     <tns:segundoNombre>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:segundoNombre"/>
                     </tns:segundoNombre>
                     <tns:municipioExpedicion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:municipioExpedicion"/>
                     </tns:municipioExpedicion>
                     <tns:departamentoExpedicion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:departamentoExpedicion"/>
                     </tns:departamentoExpedicion>
                     <tns:fechaExpedicion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:fechaExpedicion"/>
                     </tns:fechaExpedicion>
                     <tns:estadoCedula>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:estadoCedula"/>
                     </tns:estadoCedula>
                     <tns:numResolucion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:numResolucion"/>
                     </tns:numResolucion>
                     <tns:anoResolucion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:anoResolucion"/>
                     </tns:anoResolucion>
                     <tns:genero>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:genero"/>
                     </tns:genero>
                     <tns:fechaNacimiento>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:fechaNacimiento"/>
                     </tns:fechaNacimiento>
                     <tns:lugarNacimiento>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:lugarNacimiento"/>
                     </tns:lugarNacimiento>
                     <tns:informante>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:informante"/>
                     </tns:informante>
                     <tns:serial>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:serial"/>
                     </tns:serial>
                     <tns:fechaDefuncion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:fechaDefuncion"/>
                     </tns:fechaDefuncion>
                     <tns:lugarNovedad>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:lugarNovedad"/>
                     </tns:lugarNovedad>
                     <tns:lugarPreparacion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:lugarPreparacion"/>
                     </tns:lugarPreparacion>
                     <tns:grupoSanguineo>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:grupoSanguineo"/>
                     </tns:grupoSanguineo>
                     <tns:estatura>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:estatura"/>
                     </tns:estatura>
                     <tns:fechaReferencia>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:fechaReferencia"/>
                     </tns:fechaReferencia>
                     <tns:fechaAfectacion>
                        <xsl:value-of select="/ns0:consultarCedulasResponse/ns0:return/ns0:datosCedulas/ns0:datos/ns0:fechaAfectacion"/>
                     </tns:fechaAfectacion>
                  </tns:datos>
               </tns:datosCedulas>
            </xsl:if>
         </tns:return>
      </tns:consultarCedulasResponse>
   </xsl:template>
</xsl:stylesheet>